### ISSUE TITLE
bpy.types.Scene.pbe may be unregistered when BAM exporter try to remove that

### ISSUE THREAD

**Issue by sanguinariojoe** [tobspr/Panda3D-Bam-Exporter#4]
Linux, Blender 2.74

When I'm disabling the plugin right after launching blender, it is returning an exception because bpy.types.Scene has not the pbe attribute, probably because the plugin has not registered it yet.

As a workaround, I suggest replacing in Exporter.py the following line:
`del bpy.types.Scene.pbe`
by:

```
try:
    del bpy.types.Scene.pbe
except AttributeError:
    pass
```

**Comment by tobspr** [comment]
Thanks, comitted your fix here aswell! :)
