### ISSUE TITLE
Failure unloading the same module several times

### ISSUE THREAD

**Issue by sanguinariojoe** [tobspr/Panda3D-Bam-Exporter#5]
Linux, Blender 2.74

When the plugin is enabled and disabled several times, it is returning an exception because some modules are unloaded several times. It is caused by a constantly growing pbe_loaded_module_list variable.

Along this line, I suggest adding the following line:
`pbe_loaded_module_list.clear()`
at the end of the function unload_modules() in the file **init**.py (at the root of the plugin)

**Comment by tobspr** [comment]
Thanks for the suggestion, I committed your fix! :)
